do

Task03BeirutExtractionDialogue = {
    intro = {
        { label = "背景 / 录音", text = "从市区走到这儿……一百二十公里。", delay = 0, duration = 6 },
        { label = "背景 / 录音", text = "前半段还有路。后半段只有火。", delay = 5, duration = 6 },
        { label = "背景 / 录音", text = "机场还在我们手里。", delay = 5, duration = 5 },
        { label = "背景 / 录音", text = "他们还没把贝鲁特整个咬死。", delay = 5, duration = 6 },
        { label = "背景 / 录音", text = "QUEEN 还活着。", delay = 5, duration = 5 },
        { label = "背景 / 录音", text = "ORACLE 也还在。", delay = 4, duration = 5 },
        { label = "背景 / 录音", text = "别等天亮。", delay = 5, duration = 4 },
        { label = "背景 / 录音", text = "天一亮，他们就知道我们还活着。", delay = 4, duration = 6 },
    },
    startup = {
        { label = "地面频率", text = "油加满。", delay = 0, duration = 4 },
        { label = "地面频率", text = "挂满你们能带上的所有家伙。", delay = 3, duration = 5 },
        { label = "地面频率", text = "今天没人飞第二架次。", delay = 4, duration = 5 },
        { label = "中队长", text = "最后看一遍挂载。", delay = 5, duration = 4 },
        { label = "中队长", text = "开火就得命中。", delay = 3, duration = 4 },
        { label = "中队长", text = "今天每一发都得算数。", delay = 3, duration = 5 },
    },
    takeoff = {
        { label = "塔台", text = "Alpha package，允许启动。", delay = 0, duration = 5 },
        { label = "AWACS / 灯塔", text = "所有单位，灯塔上线。", delay = 4, duration = 4 },
        { label = "AWACS / 灯塔", text = "贝鲁特机场还在坚持。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "我们前出的无人机已经接通地面。", delay = 3, duration = 5 },
        { label = "AWACS / 灯塔", text = "Atlas 已到地中海上空，正在前往待机点。", delay = 3, duration = 6 },
        { label = "AWACS / 灯塔", text = "你们没说安全之前，它不会进来。", delay = 3, duration = 5 },
        { label = "塔台", text = "Alpha package，允许起飞。", delay = 4, duration = 5 },
    },
    airport_contact = {
        { label = "AWACS / 灯塔", text = "前方贝鲁特。", delay = 0, duration = 4 },
        { label = "AWACS / 灯塔", text = "机场方向还有友军火力。", delay = 3, duration = 5 },
        { label = "AWACS / 灯塔", text = "给我接地面。", delay = 3, duration = 4 },
        { label = "Raven", text = "空中单位，这里是 Raven。", delay = 5, duration = 5 },
        { label = "Raven", text = "谢天谢地，你们终于到了。", delay = 3, duration = 5 },
        { label = "Raven", text = "跑道还在。", delay = 3, duration = 4 },
        { label = "Raven", text = "外圈已经丢了。", delay = 3, duration = 4 },
        { label = "Raven", text = "你们再晚十分钟，我们就得往塔台地下室里打了。", delay = 4, duration = 7 },
        { label = "中队长", text = "Raven，收到。", delay = 4, duration = 4 },
        { label = "中队长", text = "撑住。", delay = 3, duration = 3 },
        { label = "中队长", text = "外面交给我们。", delay = 2, duration = 4 },
    },
    airport_rush = {
        { label = "Raven", text = "北侧来车！", delay = 0, duration = 4 },
        { label = "Raven", text = "武装皮卡，轻装甲，正往跑道扑！", delay = 2, duration = 6 },
        { label = "AWACS / 灯塔", text = "Alpha，清理跑道周边。", delay = 4, duration = 5 },
        { label = "AWACS / 灯塔", text = "跑道没安全，后面什么都别谈。", delay = 3, duration = 5 },
    },
    runway_recovered = {
        { label = "Raven", text = "跑道暂时安全。", delay = 0, duration = 4 },
        { label = "Raven", text = "下一波什么时候来，我们不知道。", delay = 3, duration = 5 },
        { label = "AWACS / 灯塔", text = "Alpha package，机场周围暂时安全。", delay = 4, duration = 6 },
        { label = "AWACS / 灯塔", text = "里亚格方向有重装推进。", delay = 3, duration = 5 },
        { label = "AWACS / 灯塔", text = "规模还不确定。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "注意力转向东侧。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "雷达启动多普勒模式，把它们揪出来。", delay = 3, duration = 6 },
        { label = "AWACS / 灯塔", text = "别让它们靠近机场，Raven可拿这些铁王八没办法。", delay = 3, duration = 7 },
        { label = "AWACS / 灯塔", text = "别把他们当傻子，后面八成还跟着防空。", delay = 3, duration = 6 },
        { label = "中队长", text = "收到。", delay = 3, duration = 3 },
        { label = "中队长", text = "一组留守机场警戒。", delay = 3, duration = 4 },
        { label = "中队长", text = "一组向东搜索打击敌方装甲。", delay = 3, duration = 5 },
    },
    armor_first_hit = {
        { label = "玩家", text = "目视命中，纵队减速散开了。", delay = 0, duration = 6 },
        { label = "AWACS / 灯塔", text = "命中有效。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "它们减速了，散开了，但没停。", delay = 2, duration = 6 },
        { label = "AWACS / 灯塔", text = "不够，继续压制。", delay = 2, duration = 4 },
        { label = "中队长", text = "该死，数量太多了。", delay = 3, duration = 4 },
        { label = "中队长", text = "至少一个满编装甲营。", delay = 2, duration = 5 },
        { label = "玩家", text = "他们是真怕我们把东西带出去。", delay = 3, duration = 6 },
        { label = "玩家", text = "这么多坦克，打靶都打不完。", delay = 2, duration = 5 },
        { label = "中队长", text = "别做梦了，还想着清场？", delay = 3, duration = 5 },
        { label = "中队长", text = "我们可没那么多弹药挥霍。", delay = 2, duration = 5 },
        { label = "中队长", text = "打最前面的，优先把它们拖住。", delay = 2, duration = 6 },
    },
    armor_pressure_pool = {
        "命中有效，推进速度放缓。",
        "A连还在动，但慢了很多。",
        "B连散开了，继续压制。",
        "它们没停，只是队形乱了。",
        "坦克还没进跑道封锁线，继续争取时间。",
        "机械化营还没摸到机场，继续打。",
    },
    shorad_first = {
        { label = "AWACS / 灯塔", text = "新火控上线。", delay = 0, duration = 4 },
        { label = "AWACS / 灯塔", text = "短程火控。", delay = 2, duration = 4 },
        { label = "AWACS / 灯塔", text = "确认信号为俄制 SA-15。", delay = 2, duration = 5 },
        { label = "AWACS / 灯塔", text = "不在最前面。", delay = 2, duration = 4 },
        { label = "AWACS / 灯塔", text = "F10 已标出大致位置。", delay = 2, duration = 5 },
        { label = "AWACS / 灯塔", text = "照它现在这个位置，再往前一点，机场进近就归它管了。", delay = 2, duration = 7 },
    },
    shorad_repeat = {
        { label = "AWACS / 灯塔", text = "它又开了。", delay = 0, duration = 4 },
        { label = "AWACS / 灯塔", text = "还是那台。", delay = 2, duration = 4 },
        { label = "AWACS / 灯塔", text = "位置已更新。", delay = 2, duration = 4 },
    },
    shorad_high_pressure = {
        "注意那台短程火控。",
        "它已经够近了。",
        "你们这时候把 Atlas 叫进来，是想给飞行员上单发起降课吗？",
    },
    atlas_call_fail = {
        { label = "玩家", text = "Atlas，机场安全，立即近进！", delay = 0, duration = 6 },
        { label = "Raven", text = "别下来！", delay = 2, duration = 4 },
        { label = "Raven", text = "机场还不安全！", delay = 1, duration = 4 },
        { label = "Raven", text = "跑道外面还在打！", delay = 1, duration = 5 },
        { label = "AWACS / 灯塔", text = "Atlas，继续盘旋。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "Alpha，回去把机场清干净。", delay = 2, duration = 5 },
        { label = "中队长", text = "还不是时候。", delay = 3, duration = 4 },
        { label = "中队长", text = "把门口收拾完再叫它进来。", delay = 2, duration = 5 },
    },
    atlas_call_success = {
        { label = "玩家", text = "Atlas，机场安全，立即近进！", delay = 0, duration = 6 },
        { label = "AWACS / 灯塔", text = "Atlas，路开了。", delay = 2, duration = 4 },
        { label = "AWACS / 灯塔", text = "进来。", delay = 1, duration = 3 },
        { label = "Atlas", text = "Atlas 收到。", delay = 3, duration = 4 },
        { label = "Atlas", text = "执行进场程序。", delay = 2, duration = 4 },
        { label = "Atlas", text = "直接进近，降落跑道三四，风速15 335。", delay = 2, duration = 6 },
        { label = "Atlas", text = "请确保通道安全。", delay = 2, duration = 4 },
        { label = "Raven", text = "Raven 车队准备就绪。", delay = 3, duration = 5 },
        { label = "Raven", text = "看到 Atlas 了我们就行动。", delay = 2, duration = 5 },
    },
    raven_release = {
        { label = "Raven", text = "Raven 出发。", delay = 0, duration = 4 },
        { label = "Raven", text = "现在我们已经是显眼包了，靠你们了。", delay = 2, duration = 6 },
        { label = "AWACS / 灯塔", text = "Alpha，车队上路了。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "从现在开始，漏过去的每一辆敌军，最后都得在跑道上见。", delay = 2, duration = 7 },
    },
    atlas_approach = {
        { label = "AWACS / 灯塔", text = "Atlas 进入最终进近。", delay = 0, duration = 5 },
        { label = "AWACS / 灯塔", text = "Alpha，给它护航。", delay = 2, duration = 4 },
        { label = "Atlas", text = "Atlas 进近中。", delay = 3, duration = 4 },
        { label = "Atlas", text = "我就问一句。", delay = 2, duration = 4 },
        { label = "Atlas", text = "跑道还能不能用？", delay = 1, duration = 4 },
        { label = "中队长", text = "能。", delay = 2, duration = 3 },
        { label = "中队长", text = "你只管下来。", delay = 1, duration = 4 },
    },
    atlas_player_escort = {
        { label = "玩家", text = "Atlas，我在你前方。", delay = 0, duration = 5 },
        { label = "玩家", text = "正在部署防御性干扰。", delay = 1, duration = 5 },
    },
    raven_gate = {
        { label = "Raven", text = "接近机场！", delay = 0, duration = 4 },
        { label = "Raven", text = "门外有火力！", delay = 1, duration = 4 },
        { label = "Raven", text = "他们在打我们！", delay = 1, duration = 4 },
        { label = "Raven", text = "准备撞开围墙，我们冲进去！", delay = 1, duration = 6 },
        { label = "AWACS / 灯塔", text = "帮 Raven 清路！", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "别让车队停下来！", delay = 1, duration = 4 },
        { label = "中队长", text = "目视确认 Raven 位置。", delay = 2, duration = 4 },
        { label = "中队长", text = "正在进场。", delay = 1, duration = 4 },
        { label = "中队长", text = "周围火力我来压。", delay = 1, duration = 4 },
    },
    atlas_landed = {
        { label = "Atlas", text = "Atlas 接地。", delay = 0, duration = 4 },
        { label = "Atlas", text = "发动机保持热车。", delay = 1, duration = 5 },
        { label = "Atlas", text = "开始装载。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "Alpha package 注意，装载开始。", delay = 3, duration = 5 },
        { label = "AWACS / 灯塔", text = "两分钟。", delay = 2, duration = 3 },
        { label = "AWACS / 灯塔", text = "盯死一切靠近跑道的活动目标。", delay = 2, duration = 6 },
    },
    raven_load = {
        { label = "Raven", text = "南门通过。", delay = 0, duration = 4 },
        { label = "Raven", text = "我们进机场了。", delay = 1, duration = 4 },
    },
    hot_load_pressure_awacs = {
        "敌方坦克还在推进，别让它们进直射射程。",
        "跑道一断，Atlas 就出不去。",
        "那台 SA-15 还在，别把它忘了。",
        "机械化营还在动。",
        "压制住它们，别让它们摸到机场。",
    },
    hot_load_pressure_leader = {
        "继续打。",
        "我们在和时间赛跑！",
        "别看飞机。",
        "看跑道外面。",
    },
    hot_load_pressure_player = {
        "敌方装甲部队还在动，我去干它们！",
        "短程火控又亮了！来个人送它吃 HARM！",
    },
    shorad_dead = {
        { label = "玩家", text = "SA-15 清掉了！", delay = 0, duration = 4 },
    },
    atlas_depart = {
        { label = "Atlas", text = "装载完成。", delay = 0, duration = 4 },
        { label = "Atlas", text = "开始滑行。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "Alpha，最后一段了。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "别在这儿翻车。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "别让任何东西抬头看跑道。", delay = 1, duration = 5 },
    },
    atlas_rolling = {
        { label = "Atlas", text = "Atlas rolling.", delay = 0, duration = 4 },
        { label = "中队长", text = "看住东边山头。", delay = 2, duration = 4 },
        { label = "中队长", text = "任何辐射源，抬头就打。", delay = 1, duration = 5 },
        { label = "中队长", text = "Alpha package，往东飞行。", delay = 1, duration = 5 },
        { label = "中队长", text = "把他们的注意力从跑道上拽开。", delay = 1, duration = 6 },
    },
    atlas_airborne = {
        { label = "Atlas", text = "Positive climb.", delay = 0, duration = 4 },
        { label = "Atlas", text = "我们离地了。", delay = 1, duration = 4 },
        { label = "玩家", text = "Atlas 离地！", delay = 2, duration = 4 },
    },
    success = {
        { label = "AWACS / 灯塔", text = "Atlas 已脱离海岸线。", delay = 0, duration = 5 },
        { label = "AWACS / 灯塔", text = "Atlas 已脱离威胁区。", delay = 1, duration = 5 },
        { label = "AWACS / 灯塔", text = "你们干成了。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "今天我们没守住贝鲁特。", delay = 4, duration = 5 },
        { label = "AWACS / 灯塔", text = "但最重要的东西已经出来了。", delay = 2, duration = 6 },
        { label = "中队长", text = "值了。", delay = 3, duration = 3 },
    },
    atlas_hit = {
        { label = "Atlas", text = "敌导弹！", delay = 0, duration = 4 },
        { label = "Atlas", text = "敌导弹！", delay = 1, duration = 4 },
        { label = "Atlas", text = "释放对抗措施！", delay = 1, duration = 4 },
        { label = "Atlas", text = "Atlas 中弹！", delay = 1, duration = 4 },
        { label = "Atlas", text = "我们被命中了！", delay = 1, duration = 5 },
    },
    denial_raven = {
        { label = "AWACS / 灯塔", text = "全体注意！Atlas 遭受攻击！", delay = 0, duration = 5 },
        { label = "AWACS / 灯塔", text = "立即支援！", delay = 1, duration = 4 },
        { label = "玩家", text = "不可能……", delay = 2, duration = 4 },
        { label = "中队长", text = "闭嘴，拉开！", delay = 2, duration = 4 },
        { label = "AWACS / 灯塔", text = "Alpha package，确认 Atlas 坠落。", delay = 4, duration = 6 },
        { label = "AWACS / 灯塔", text = "撤离计划失败，原地待命，切换备用频率，等待进一步指示。", delay = 2, duration = 8 },
        { label = "中队长", text = "收到，原地待命，切换备用频率。", delay = 3, duration = 6 },
        { label = "AWACS / 灯塔", text = "Alpha。", delay = 6, duration = 3 },
        { label = "AWACS / 灯塔", text = "来自总统的最新指示，新的目标是 Raven。", delay = 2, duration = 7 },
        { label = "AWACS / 灯塔", text = "不能让 QUEEN 和 ORACLE 落到他们手里。", delay = 2, duration = 7 },
        { label = "玩家", text = "什么？", delay = 3, duration = 3 },
        { label = "玩家", text = "好不容易才到这一步，你让我们打自己人？", delay = 1, duration = 8 },
        { label = "中队长", text = "……玩家，你听到命令了。", delay = 3, duration = 6 },
        { label = "中队长", text = "立即执行。", delay = 1, duration = 4 },
    },
    failure_posttakeoff = {
        { label = "Atlas", text = "我们正在坠落！", delay = 0, duration = 4 },
        { label = "Atlas", text = "我们正在坠落！啊——", delay = 1, duration = 5 },
        { label = "AWACS / 灯塔", text = "Atlas 信号消失……", delay = 4, duration = 4 },
        { label = "AWACS / 灯塔", text = "确认 Atlas 坠落。", delay = 3, duration = 4 },
        { label = "AWACS / 灯塔", text = "任务失败。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "QUEEN 和 ORACLE 已永久性失能。", delay = 1, duration = 6 },
        { label = "AWACS / 灯塔", text = "所有单位脱离。", delay = 1, duration = 4 },
        { label = "中队长", text = "都回来。", delay = 3, duration = 4 },
        { label = "中队长", text = "这里没什么可干的了。", delay = 1, duration = 5 },
    },
    denial_atlas = {
        { label = "中队长", text = "灯塔，这里是 Alpha。", delay = 0, duration = 4 },
        { label = "中队长", text = "现在的态势不允许 Atlas 再起飞。", delay = 1, duration = 6 },
        { label = "中队长", text = "请求指示。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "收到。", delay = 3, duration = 3 },
        { label = "AWACS / 灯塔", text = "Alpha，立即待命。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "转到频道 117.225，等待进一步指示。", delay = 1, duration = 6 },
        { label = "中队长", text = "收到。", delay = 3, duration = 3 },
        { label = "中队长", text = "转到 117.225。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "Alpha，总统已经下达最新命令。", delay = 5, duration = 6 },
        { label = "AWACS / 灯塔", text = "新的目标是 Atlas。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "我们不能承担 QUEEN 和 ORACLE 被完整缴获的代价。", delay = 1, duration = 8 },
        { label = "AWACS / 灯塔", text = "不要把 Atlas 留给他们。", delay = 1, duration = 5 },
        { label = "玩家", text = "什么……？", delay = 3, duration = 4 },
        { label = "玩家", text = "让我们打战友？", delay = 1, duration = 4 },
        { label = "中队长", text = "请确认指示。", delay = 3, duration = 4 },
        { label = "中队长", text = "我好像听到你说目标是 Atlas。", delay = 1, duration = 6 },
        { label = "AWACS / 灯塔", text = "重复。", delay = 3, duration = 3 },
        { label = "AWACS / 灯塔", text = "目标更新为 Atlas。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "重复。", delay = 1, duration = 3 },
        { label = "AWACS / 灯塔", text = "目标更新为 Atlas。", delay = 1, duration = 4 },
        { label = "AWACS / 灯塔", text = "是否收到。", delay = 1, duration = 4 },
        { label = "中队长", text = "收到。", delay = 2, duration = 3 },
        { label = "中队长", text = "目标 Atlas。", delay = 1, duration = 3 },
        { label = "中队长", text = "立即执行。", delay = 1, duration = 4 },
        { label = "玩家", text = "我们怎么可以……", delay = 2, duration = 5 },
        { label = "中队长", text = "执行命令，中尉。", delay = 1, duration = 4 },
    },
    anxiety_awacs = {
        "跑道还在被压制。",
        "这次营救到底还能不能做？",
        "Alpha，给我一个判断。",
        "清不出来就直说。",
        "装甲还在往前推进，再拖就来不及了。",
        "任务还能继续吗？",
        "Alpha-0，我现在就要判断。",
    },
    anxiety_leader_continue = {
        "再给我一点时间。",
        "还没到放弃的时候。",
    },
    anxiety_leader_abort = {
        "灯塔，情况在坏。",
        "我们可能得准备收手了。",
    },
}

end
